### ISSUE TITLE
RGB files

### ISSUE THREAD

**Issue by mak-en** [lmomoy/CENet#2]
Dear Authors, I'd like to ask which RGB files (unsynced+unrectified or synced+rectified) are downloaded, when using `./download/rgb_train_downloader.sh` and `download/rgb_val_downloader.sh` scripts?

**Comment by lmomoy** [comment]
> Dear Authors, I'd like to ask which RGB files (unsynced+unrectified or synced+rectified) are downloaded, when using `./download/rgb_train_downloader.sh` and `download/rgb_val_downloader.sh` scripts?

![image](https://github.com/lmomoy/CHNet/assets/49771303/8c968e3e-8540-4195-8397-ff79137839cb)
I think it is sync image, and you can refer to the screenshot.
