### ISSUE TITLE
Pre-trained models and the two variants

### ISSUE THREAD

**Issue by zhengyu2023** [lmomoy/CENet#3]
You mentioned two variants in your paper, CHNet-S and CHNet-L, but I couldn't find the relevant definitions in the code. Could you please explain how to use the different variants?Can I get your pre-trained model?

**Comment by lmomoy** [comment]
The code is based on CHNet-S, and you can modify the dimension accroding to our paper's description.
Please give me your email and I will send you the pre-trained model.
